# Generated by korniychuk/GokuRakuJoudo .github/scripts/bump-tap.sh — do not edit by hand.
class Goku < Formula
  desc "Karabiner configurator (fork: scan_next_track/scan_previous_track + auto-synced upstream)"
  homepage "https://github.com/korniychuk/GokuRakuJoudo"
  url "https://github.com/korniychuk/GokuRakuJoudo/releases/download/v0.8.0-ankor.4/goku-aarch64-apple-darwin.zip"
  version "0.8.0.4"
  sha256 "9ea0b5b3f548a3899334a0d9502c1057d97701278c7134ffb083655b0a5ab6e8"

  depends_on :macos
  depends_on arch: :arm64
  depends_on "joker"
  depends_on "watchexec"

  def install
    bin.install "goku"
    bin.install "gokuw"
  end

  service do
    run opt_bin/"gokuw"
    environment_variables PATH: std_service_path_env
    keep_alive true
    run_at_load true
    log_path "#{Dir.home}/Library/Logs/goku.log"
    error_log_path "#{Dir.home}/Library/Logs/goku.log"
  end

  test do
    assert_predicate bin/"goku", :executable?
  end
end
