# Generated by korniychuk/GokuRakuJoudo .github/scripts/bump-tap.sh — do not edit by hand.
class Goku < Formula
  desc "Karabiner configurator (fork: scan_next_track/scan_previous_track + auto-synced upstream)"
  homepage "https://github.com/korniychuk/GokuRakuJoudo"
  url "https://github.com/korniychuk/GokuRakuJoudo/releases/download/v0.5.1-ankor.1/goku-aarch64-apple-darwin.zip"
  version "0.5.1.1"
  sha256 "d88c89fada59b368f6dda114e864cc69f760c2008832e38c129187e65821c06d"

  depends_on arch: :arm64
  depends_on "joker"
  depends_on "watchexec"

  def install
    bin.install "goku"
    bin.install "gokuw"
  end

  service do
    run opt_bin/"gokuw"
    environment_variables PATH: std_service_path_env
    keep_alive true
    run_at_load true
    log_path "#{Dir.home}/Library/Logs/goku.log"
    error_log_path "#{Dir.home}/Library/Logs/goku.log"
  end

  test do
    assert_predicate bin/"goku", :executable?
  end
end
